nodeLinker: node-modules
enableGlobalCache: true

compressionLevel: mixed

packageExtensions:
  vite@*:
    peerDependencies:
      "@types/node": "*"
  vitest@*:
    peerDependencies:
      "@types/node": "*" 